### PR TITLE
Add support for saving JSON files of Advanced Custom Fields Pro

### PR DESCRIPTION
**Pull request by iMicknl**
When running the theme in development mode (through gulp) a snippet will be injected into functions.php that makes sure that the field data is saved into the acf-json folder of the development theme.

### CODE REVIEW

**Comment by Maximilianos** [comment]
Hey @iMicknl , thanks for the pr! One minor thing, is it necessary for the acf-json folder to exist in order for this to work? Because I would rather not have it in there for people who don't care about it

**Comment by iMicknl** [comment]
That was something I was not sure about either. If you don't have the folder; it won't work as far as I tested. In that case it should be documented that you need to create an acf-json folder in your 'theme' folder.

**Comment by iMicknl** [comment]
@Maximilianos what do you think? So I can do the changes and finish this PR. 👍

**Comment by Maximilianos** [comment]
@iMicknl I haven't been able to make the time to test this further, I apologize. I will need a little more time

**Comment by iMicknl** [comment]
@Maximilianos no problem! Wasn't sure if it was my turn to do something or that you needed to review it.

**Comment by Maximilianos** [comment]
> If you don't have the folder; it won't work as far as I tested.

@iMicknl can you be a bit more specific, please? What part didn't work? Did the gulp task fail or did the acf php functions fail?

**Comment by iMicknl** [comment]
Sorry, I totally missed your comment. When you don't have the folder, it won't be created by Advanced Custom Fields automatically.

**Pull request closed without merging**
